# Using Multi-Stage Build
FROM registry.access.redhat.com/ubi8/ubi:latest AS builder

# Grabbing jq to get server.jar
RUN curl -o jq -sL https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64 && chmod +x jq

# Pulling down loatest Minecraft Server jarfile
RUN "{{ curl_command }}"

# Creating eula.txt
RUN echo "eula=true" > /tmp/eula.txt

# Start Final Build Stage
FROM registry.access.redhat.com/ubi8/openjdk-17-runtime@sha256:1a40771ffd18a688a4492f319814af5d2e3377eb293c69ca682f29a3a86635ab

# Label Image with important information
LABEL builder="{{ mineops_email }}" \
      application="minecraft-server" \
      java_version="{{ java_version }}" \
      minecraft_version="{{ minecraft_version }}"

RUN mkdir /minecraft

WORKDIR /minecraft

COPY --from=builder /tmp/eula.txt .
COPY --from=builder /tmp/server.jar .

CMD ["java", "-jar", "server.jar"]
