apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-mineops
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: files/ArgoCD/appofapps/apps
    repoURL: https://github.com/KyWa/mineOps.git
    targetRevision: master
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
